services:
  - type: web
    name: vanier-ceramic-shop
    env: python
    plan: free
    buildCommand: './build.sh'
    startCommand: 'uv run gunicorn main.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: vanier-ceramic-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_STORAGE_BUCKET_NAME
        value: vanier-ceramic-shop-images-juan-2026
      - key: RENDER
        value: '1'
      - key: WEB_CONCURRENCY
        value: '4'
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false

databases:
  - name: vanier-ceramic-db
    plan: free
    databaseName: vanier-ceramic-shop
    user: vanier-ceramic-shop
